#!/bin/bash
# Download the third-party browser assets Tusk ships in the wheel and the
# container image, so the UI never needs the internet. Pinned versions;
# output goes to src/tusk/studio/static/vendor/ (committed).
#
#   bash scripts/vendor.sh          # download everything
#   make css                        # then compile Tailwind (see Makefile)
set -euo pipefail

VENDOR_DIR="src/tusk/studio/static/vendor"
mkdir -p "$VENDOR_DIR/fonts"

ALPINE=3.14.9
HTMX=2.0.4
LUCIDE=0.469.0
MAPLIBRE=4.1.0
PROJ4=2.15.0
DAGRE=1.1.4
CHARTJS=4.5.1
GRIDSTACK=10.3.1

get() { # get <url> <dest>
  echo "  $(basename "$2")  <-  $1"
  curl -fsSL --retry 3 -o "$2" "$1"
}

get "https://cdn.jsdelivr.net/npm/alpinejs@${ALPINE}/dist/cdn.min.js"            "$VENDOR_DIR/alpine.min.js"
get "https://cdn.jsdelivr.net/npm/htmx.org@${HTMX}/dist/htmx.min.js"              "$VENDOR_DIR/htmx.min.js"
get "https://cdn.jsdelivr.net/npm/lucide@${LUCIDE}/dist/umd/lucide.min.js"        "$VENDOR_DIR/lucide.min.js"
get "https://cdn.jsdelivr.net/npm/maplibre-gl@${MAPLIBRE}/dist/maplibre-gl.js"    "$VENDOR_DIR/maplibre-gl.js"
get "https://cdn.jsdelivr.net/npm/maplibre-gl@${MAPLIBRE}/dist/maplibre-gl.css"   "$VENDOR_DIR/maplibre-gl.css"
get "https://cdn.jsdelivr.net/npm/proj4@${PROJ4}/dist/proj4.js"                   "$VENDOR_DIR/proj4.min.js"
get "https://cdn.jsdelivr.net/npm/@dagrejs/dagre@${DAGRE}/dist/dagre.min.js"     "$VENDOR_DIR/dagre.min.js"
get "https://cdn.jsdelivr.net/npm/chart.js@${CHARTJS}/dist/chart.umd.min.js"      "$VENDOR_DIR/chart.umd.min.js"
get "https://cdn.jsdelivr.net/npm/gridstack@${GRIDSTACK}/dist/gridstack-all.js"   "$VENDOR_DIR/gridstack-all.js"
get "https://cdn.jsdelivr.net/npm/gridstack@${GRIDSTACK}/dist/gridstack.min.css"  "$VENDOR_DIR/gridstack.min.css"

# Fonts: Google Fonts serves woff2 only to a modern browser UA. Download the
# CSS, then every woff2 it points at, and rewrite the URLs to local files.
FONTS_URL='https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;500&family=Instrument+Serif&display=swap'
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36'
echo "  fonts.css  <-  Google Fonts (Geist, Geist Mono, Instrument Serif)"
curl -fsSL --retry 3 -A "$UA" -o "$VENDOR_DIR/fonts.src.css" "$FONTS_URL"
python3 - "$VENDOR_DIR" <<'PY'
import re, sys, pathlib, urllib.request, hashlib
vendor = pathlib.Path(sys.argv[1])
css = (vendor / "fonts.src.css").read_text()
seen = {}
def local(m):
    url = m.group(1)
    if url not in seen:
        name = hashlib.sha1(url.encode()).hexdigest()[:10] + ".woff2"
        urllib.request.urlretrieve(url, vendor / "fonts" / name)
        seen[url] = name
    return f"url(/static/vendor/fonts/{seen[url]})"
out = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", local, css)
(vendor / "fonts.css").write_text("/* Generated by scripts/vendor.sh from Google Fonts; files in fonts/ */\n" + out)
(vendor / "fonts.src.css").unlink()
print(f"  {len(seen)} font files")
PY

echo
ls -lh "$VENDOR_DIR" "$VENDOR_DIR/fonts" | head -40
